import { PETS } from './pet.js';
import { petArt } from './pet-art.js';
import { BOND_LEVELS, bondLevel, petName } from '../../core/pet-bonds.js';
import { MEAL_COST, PET_FOODS, PET_BELONGINGS, petCareStatus } from '../../core/pet-care.js';
import { icon } from '../../ui/icons.js';

export const escapePetText = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
export const careIcon = kind => `<svg viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${kind === 'food' ? '<path d="M4 16h24l-3 9H7z"/><path d="M3 16h26M10 10c-3-3 3-3 0-6m7 6c-3-3 3-3 0-6m7 6c-3-3 3-3 0-6"/><path d="M13 20h6"/>' : kind === 'ball' ? '<circle cx="16" cy="16" r="11"/><path d="M6 12c8 3 12 8 14 14M12 6c3 8 8 12 14 14M8 24 24 8"/>' : '<path d="M8 17c-4-6 4-11 8-5 4-6 12-1 8 5l-8 8z"/><path d="M7 4v4M5 6h4m15-2v4m-2-2h4"/>'}</svg>`;
export function foodArt(food, fabric) {
  return `<svg viewBox="0 0 100 76" aria-hidden="true"><ellipse cx="50" cy="65" rx="33" ry="6" fill="#4c3025" opacity=".09"/><path d="M16 34h68l-8 26q-26 10-52 0z" fill="${fabric.color}"/><ellipse cx="50" cy="34" rx="34" ry="14" fill="${fabric.dark}"/><ellipse cx="50" cy="33" rx="29" ry="10" fill="#654c39"/>${[[33, 31], [43, 26], [57, 29], [67, 32], [50, 35], [38, 37], [62, 38]].map(([x, y], i) => `<ellipse cx="${x}" cy="${y}" rx="${food.id === 'supper' ? 8 : 5}" ry="4" transform="rotate(${i * 27} ${x} ${y})" fill="${food.color}"/>`).join('')}<path d="M17 35q33 23 66 0" fill="none" stroke="${fabric.color}" stroke-width="4"/><path d="M45 52q5-6 10 0l-5 5z" fill="#fff5e5"/></svg>`;
}
export function petCardMarkup(state, now) {
  const id = state.pet, pet = PETS[id], bond = state.petBonds[id], level = bondLevel(bond), care = petCareStatus(bond, now);
  const fabric = PET_BELONGINGS.find(item => item.id === bond.care.fabric), petLabel = escapePetText(petName(state));
  return `<div class="pet-card" data-pet-id="${id}">
    <header class="pet-card-identity"><div class="pet-avatar-mark">${petArt(id)}</div><div><h2>${petLabel}</h2><button id="pet-edit-name" aria-label="Rename ${petLabel}">${icon('build')}</button><span class="pet-bond-title">${level.title}</span></div></header>
    <form id="pet-name-form" hidden><label class="sr-only" for="pet-name">Pet name</label><input id="pet-name" maxlength="24" value="${petLabel}" autocomplete="off" required><button type="submit">Save</button></form>
    <div class="pet-bond-heading"><span aria-label="${bond.affection} hearts">${icon('heart')} ${bond.affection}</span><span>${bond.minutes ? `${bond.minutes} min together` : pet.kind}</span></div>
    <div class="pet-bond-track" role="progressbar" aria-label="Bond with ${petLabel}" aria-valuemin="${level.next ? level.at : 0}" aria-valuemax="${level.next?.at || Math.max(60, bond.affection)}" aria-valuenow="${bond.affection}"><i style="width:${level.progress * 100}%"></i></div>
    <div class="pet-care-actions">
      <button id="pet-now" data-pet-ritual="cuddle" aria-label="Pet ${petLabel}">${careIcon('heart')}<strong>Pet</strong><small>♡</small></button>
      <button id="pet-play" data-pet-ritual="play" aria-label="Play with ${petLabel}${care.playReady ? ', earn one heart' : `, heart in ${care.playMinutes} minutes`}">${careIcon('ball')}<strong>Play</strong><small>${care.playReady ? '+1 ♡' : `${care.playMinutes}m ♡`}</small></button>
      <button id="pet-feed" aria-expanded="false" aria-controls="pet-meals">${careIcon('food')}<strong>Feed</strong><small>${care.full ? 'Full ♡' : `${MEAL_COST} ◉`}</small></button>
    </div>
    <div id="pet-meals" class="pet-meals" hidden>${PET_FOODS[id].map(food => `<button id="pet-meal-${food.id}" data-pet-meal="${food.id}" ${care.full || state.house.coins < MEAL_COST ? 'disabled' : ''}>${foodArt(food, fabric)}<span>${food.name}</span><small>${care.full ? `${care.mealMinutes}m` : `${MEAL_COST} ◉ · +1 ♡`}</small></button>`).join('')}<span class="pet-meal-note">${care.full ? `Full for ${care.mealMinutes} min` : state.house.coins < MEAL_COST ? `${MEAL_COST - state.house.coins} more coins` : `${state.house.coins} ◉`}</span></div>
    <p id="pet-ritual-status" class="pet-care-receipt" role="status"></p>
    <button class="pet-invite" id="pet-invite">${icon('cat')} Sit with me ${icon('arrow')}</button>
    ${level.index >= 2 ? `<button class="pet-invite pet-nap" id="pet-nap">${icon('moon')} Nap beside me ${icon('arrow')}</button>` : ''}
    <details class="pet-details" id="pet-belongings"><summary>Little belongings <span>＋</span></summary><div class="pet-fabric-preview" style="--fabric:${fabric.color};--fabric-dark:${fabric.dark}"><div class="pet-quilt"><i>♡</i></div><span>Blanket & bowl</span></div><div class="pet-fabrics">${PET_BELONGINGS.map(item => `<button id="pet-fabric-${item.id}" data-pet-fabric="${item.id}" style="--fabric:${item.color};--fabric-dark:${item.dark}" aria-label="${item.name}${bond.care.belongings.includes(item.id) ? '' : `, ${item.price} coins`}" aria-pressed="${bond.care.fabric === item.id}"><i></i><small>${bond.care.belongings.includes(item.id) ? bond.care.fabric === item.id ? '✓' : '◦' : `${item.price} ◉`}</small></button>`).join('')}</div><div class="pet-ribbons" aria-label="Ribbon color">${BOND_LEVELS.map((item, index) => `<button id="pet-ribbon-${index}" data-pet-ribbon="${index}" aria-label="${item.keepsake}" aria-pressed="${bond.ribbon === index}" ${index > level.index ? 'disabled' : ''} style="--ribbon:${item.color}"><i>🎀</i><small>${index > level.index ? `${item.at} ♡` : item.keepsake.split(' ')[0]}</small></button>`).join('')}</div></details>
    <details class="pet-details" id="pet-friendship"><summary>Our friendship <span>${icon('heart')}</span></summary><ol class="pet-milestones">${[['A warm welcome', 8], ['Naps beside you', 24], ['A little happy dance', 60]].map(([label, hearts]) => `<li class="${bond.affection >= hearts ? 'is-unlocked' : ''}"><span>${label}</span><span>${bond.affection >= hearts ? '✓' : `${hearts} ♡`}</span></li>`).join('')}</ol>${level.index >= 3 ? `<button id="pet-dance" class="pet-invite">${icon('sun')} Happy dance</button>` : ''}</details>
    <details class="pet-details" id="pet-collection"><summary>My pets <span>${state.pets.length}</span></summary><div class="pet-options">${Object.values(PETS).map(entry => `<button data-pet-choice="${entry.id}" id="pet-choice-${entry.id}" aria-label="${state.pets.includes(entry.id) ? `Choose ${escapePetText(petName(state, entry.id))}` : `Meet ${entry.name}, ${entry.price} coins`}" aria-pressed="${id === entry.id}">${petArt(entry.id)}<span>${escapePetText(state.pets.includes(entry.id) ? petName(state, entry.id) : entry.name)}</span><small>${state.pets.includes(entry.id) ? id === entry.id ? '♡' : '' : `${entry.price} ◉`}</small></button>`).join('')}</div><div class="pet-adopt" id="pet-adopt" hidden></div></details>
  </div>`;
}
