import { PETS } from './pet.js';
import { petArt } from './pet-art.js';
import { petScene, friendshipScene } from './pet-scenes.js';
import { PET_PERSONALITIES, PET_RITUALS, BOND_LEVELS, bondLevel, petName } from '../../core/pet-bonds.js';
import { petEntity, friendshipBetween, FRIENDSHIP_MOMENTS, FRIENDSHIP_LEVELS } from '../../core/friendships.js';
import { sessionStarted } from '../../core/session.js';
import { localDate } from '../../core/state.js';
import { icon } from '../../ui/icons.js';

export const escapePetText = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const minutesLabel = minutes => minutes >= 60 ? `${Math.floor(minutes / 60)}h ${minutes % 60}m` : `${minutes} min`;
const stamp = at => new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(new Date(at));
const names = (state, ids) => ids.map(id => escapePetText(petName(state, id))).join(' & ');
const rewardBadge = (shared, hearts, friendship = false) => `<small role="img" aria-label="${shared ? 'Shared today' : `Earn ${hearts} ${friendship ? 'friendship ' : ''}${hearts === 1 ? 'heart' : 'hearts'}`}">${shared ? '✓' : `+${hearts} ♡`}</small>`;

function memories(items, pair = false) {
  if (!items.length) return `<p class="pet-empty-memory">${pair ? 'Share a moment to start.' : 'Focus together to start.'}</p>`;
  return `<ol class="pet-memories">${[...items].reverse().slice(0, 4).map(m => `<li><span class="memory-mark" aria-hidden="true">${m.kind === 'focus' ? '✦' : '♡'}</span><span>${m.kind === 'focus' ? `${m.value} min together` : m.kind === 'bond' ? BOND_LEVELS[Math.min(3, m.value)].title : m.kind === 'level' ? FRIENDSHIP_LEVELS[m.value].title : m.kind === 'play' ? 'Playdate' : m.kind === 'snack' ? 'Shared treat' : m.kind === 'quiet' ? 'Quiet company' : 'Came home'}<time>${stamp(m.at)}</time></span></li>`).join('')}</ol>`;
}

export function petPageMarkup(state, tab, friendId) {
  const id = state.pet, bond = state.petBonds[id], level = bondLevel(bond), personality = PET_PERSONALITIES[id];
  const owner = petEntity(id), buddy = state.friendships.focusBuddies[owner]?.slice(4), friends = state.pets.filter(p => p !== id);
  const today = bond.ritualDay === localDate() ? bond.rituals : [];
  const friend = friendId && friends.includes(friendId) ? friendId : friends[0];
  const friendship = friend ? friendshipBetween(state.friendships, owner, petEntity(friend)) : null;
  const pairTitle = friend ? names(state, [id, friend]) : '';
  const circle = Object.values(PETS).filter(p => state.pets.includes(p.id)).map(p => `<button class="pet-option" data-pet-choice="${p.id}" aria-pressed="${id === p.id}" aria-label="Choose ${escapePetText(petName(state, p.id))}"><span class="pet-circle-art">${petArt(p.id)}</span><strong>${escapePetText(petName(state, p.id))}</strong><span class="pet-tag">${id === p.id ? 'With you' : 'At home'}</span></button>`).join('');
  const waiting = Object.values(PETS).filter(p => !state.pets.includes(p.id)).map(p => `<button class="pet-option is-locked" data-pet-choice="${p.id}" aria-pressed="false" aria-label="Meet ${p.name}, ${p.price} coins">${petArt(p.id)}<span><strong>${p.name}</strong><span class="pet-tag is-price">${icon('sun')} ${p.price}</span></span><span class="pet-meet-arrow" aria-hidden="true">↗</span></button>`).join('');
  const sessionPair = state.session.friendPair;
  const currentCompany = sessionStarted(state.session) ? sessionPair ? names(state, sessionPair.map(member => member.slice(4))) : escapePetText(petName(state, state.session.petId || id)) : null;
  const rituals = Object.entries(PET_RITUALS).map(([kind, item]) => `<button data-pet-ritual="${kind}" id="${kind === 'cuddle' ? 'pet-now' : `pet-${kind}`}" class="pet-ritual ${today.includes(kind) ? 'is-shared' : ''}" aria-label="${kind === 'cuddle' ? `Give ${escapePetText(bond.name)} a pet` : `${item.label} with ${escapePetText(bond.name)}`}, ${today.includes(kind) ? 'Shared today' : `Earn ${personality.ritual === kind ? '2 hearts' : '1 heart'}`}"><span>${icon(item.symbol)}</span><strong>${item.label}</strong>${rewardBadge(today.includes(kind), personality.ritual === kind ? 2 : 1)}</button>`).join('');
  return `<div class="pet-notebook">
    <header class="pet-page-intro"><div><h1>Your little <em>circle.</em></h1></div><div class="pet-page-wallet">${icon('sun')} ${state.house.coins}<span>coins</span></div></header>
    <div class="pet-circle-row"><div class="pet-options pet-circle" aria-label="Your companions">${circle}</div><div class="pet-arrivals">${waiting ? `<span>Meet a friend</span><div>${waiting}</div>` : ''}</div></div>
    <div class="pet-adopt" id="pet-adopt" hidden></div>
    <div class="pet-page-grid">
      <section class="pet-character-card" aria-label="${escapePetText(bond.name)}"><div class="pet-hero"><div class="pet-portrait" id="pet-portrait">${petScene(id, BOND_LEVELS[bond.ribbon].color)}</div><div class="pet-identity"><span class="pet-trait">${personality.trait}</span><h2>${escapePetText(bond.name)}</h2></div></div><div class="pet-bond"><div class="pet-bond-heading"><strong>${level.title}</strong><span role="img" aria-label="${bond.affection} hearts">${icon('heart')} ${bond.affection}</span></div><div class="pet-bond-track" role="progressbar" aria-label="Bond with ${escapePetText(bond.name)}" aria-valuemin="${level.next ? level.at : 0}" aria-valuemax="${level.next?.at || 60}" aria-valuenow="${Math.min(bond.affection, level.next?.at || 60)}"><i style="width:${level.progress * 100}%"></i></div><div class="pet-bond-detail"><span>${minutesLabel(bond.minutes)} together</span><span role="img" aria-label="${level.next ? `${level.next.at - level.points} hearts to ${level.next.keepsake}` : 'All ribbons unlocked'}">${level.next ? `${level.next.at - level.points} ♡ → ${level.next.keepsake}` : '♡'}</span></div></div></section>
      <div class="pet-page-content"><div class="pet-page-tabs" role="tablist" aria-label="Companion pages">${['together', 'friends', 'keepsakes'].map(t => `<button role="tab" id="pet-tab-${t}" data-pet-tab="${t}" aria-selected="${tab === t}" aria-controls="pet-view-${t}" tabindex="${tab === t ? 0 : -1}">${t[0].toUpperCase() + t.slice(1)}</button>`).join('')}</div>
      <section id="pet-view-together" role="tabpanel" aria-labelledby="pet-tab-together" ${tab !== 'together' ? 'hidden' : ''}>
        <div class="pet-section-heading"><h3>Time together.</h3></div><div class="pet-rituals">${rituals}</div><p class="pet-ritual-status" id="pet-ritual-status" role="status"></p>
        <button class="pet-invite" id="pet-invite">${icon('cat')} Come sit with me <span aria-hidden="true">↗</span></button>
        <div class="pet-focus-company"><div><span class="pet-card-label">Next focus</span><h4>${buddy ? names(state, [id, buddy]) : `You & ${escapePetText(bond.name)}`}</h4></div><div class="pet-buddy-controls"><label for="pet-focus-buddy">Bring a friend</label><select id="pet-focus-buddy"><option value="">Just us</option>${friends.map(p => `<option value="${p}" ${buddy === p ? 'selected' : ''}>${escapePetText(petName(state, p))}</option>`).join('')}</select></div>${currentCompany ? `<p class="pet-current-company">This session · ${currentCompany}</p>` : ''}</div>
        <details class="pet-details"><summary>Make it personal <span aria-hidden="true">＋</span></summary><form id="pet-name-form" class="pet-name-form"><label for="pet-name">Their name</label><div><input id="pet-name" maxlength="24" value="${escapePetText(bond.name)}" autocomplete="off"><button type="submit">Save name</button></div></form><label class="pet-family-label" for="pet-family">Loved by <span>on your portraits</span></label><input id="pet-family" maxlength="24" value="${escapePetText(state.petFamily)}" placeholder="You, or both of your names" autocomplete="off"></details>
      </section>
      <section id="pet-view-friends" role="tabpanel" aria-labelledby="pet-tab-friends" ${tab !== 'friends' ? 'hidden' : ''}>
        <div class="pet-section-heading"><h3>Better together.</h3></div>
        ${friendship ? `<div class="pet-friend-picker" aria-label="Choose a friend for ${escapePetText(bond.name)}">${friends.map(p => `<button data-pet-friend="${p}" aria-pressed="${friend === p}">${petArt(p)}<span>${escapePetText(petName(state, p))}</span></button>`).join('')}</div><div class="pet-friend-scene" id="pet-friend-scene">${friendshipScene(id, friend)}<h4>${pairTitle}</h4><p>${friendship.level.title}</p></div><div class="pet-friend-progress"><span role="img" aria-label="${friendship.affection} friendship hearts">${icon('heart')} ${friendship.affection}</span><span role="img" aria-label="${friendship.level.next ? `${friendship.level.next.at - friendship.affection} friendship hearts to ${friendship.level.next.title}` : 'All friendship frames unlocked'}">${friendship.level.next ? `${friendship.level.next.at - friendship.affection} ♡ → ${friendship.level.next.title}` : '♡'}</span><div class="pet-bond-track"><i style="width:${friendship.level.progress * 100}%"></i></div></div><div class="pet-shared-moments">${Object.entries(FRIENDSHIP_MOMENTS).map(([kind, item]) => `<button data-friend-moment="${kind}" data-friend-id="${friend}">${icon(kind === 'play' ? 'sun' : kind === 'snack' ? 'leaf' : 'heart')}<strong>${item.label}</strong>${rewardBadge(friendship.rewardDay === localDate() && friendship.rewardedMoments.includes(kind), 1, true)}</button>`).join('')}</div><p id="pet-friend-status" class="pet-friend-status" role="status"></p><button id="pet-focus-pair" data-friend-id="${friend}" class="pet-pair-focus">${icon('clock')} ${sessionStarted(state.session) ? 'Choose for next focus' : 'Focus together'} <span aria-hidden="true">↗</span></button><div class="pet-pair-memories"><h4>Memories</h4>${memories(friendship.memories, true)}</div>` : '<p class="pet-empty-memory">Welcome a friend to begin.</p>'}
      </section>
      <section id="pet-view-keepsakes" role="tabpanel" aria-labelledby="pet-tab-keepsakes" ${tab !== 'keepsakes' ? 'hidden' : ''}>
        <div class="pet-section-heading"><h3>Keepsakes.</h3></div><div class="pet-ribbons" aria-label="Keepsake ribbons">${BOND_LEVELS.map((l, i) => `<button data-pet-ribbon="${i}" style="--ribbon:${l.color}" aria-label="${l.keepsake}${i > level.index ? `, ${l.at} hearts to unlock` : ''}" aria-pressed="${bond.ribbon === i}" ${i > level.index ? 'disabled' : ''}><span aria-hidden="true"></span><strong>${l.keepsake.split(' ')[0]}</strong><small>${i > level.index ? `${l.at} ♡` : bond.ribbon === i ? 'Wearing' : 'Wear'}</small></button>`).join('')}</div>
        <div class="pet-portrait-gallery"><article class="pet-keepsake-preview"><div>${petArt(id)}<span>${escapePetText(bond.name)}</span></div><button class="pet-portrait-save" id="pet-save-portrait">${icon('heart')} Save portrait</button></article>${friend ? `<article class="pet-keepsake-preview is-pair"><div><span class="pet-mini-pair">${petArt(id)}${petArt(friend)}</span><span>${pairTitle}</span></div><button class="pet-portrait-save" id="pet-save-duo" data-friend-id="${friend}">${icon('heart')} Save together</button></article>` : ''}</div><p class="pet-portrait-status" role="status"></p><details class="pet-details"><summary>Memories <span aria-hidden="true">${bond.sessions || '♡'}</span></summary>${memories(bond.memories)}</details>
      </section></div>
    </div>
  </div>`;
}
