import { PETS } from './pet.js';
import { petArt } from './pet-art.js';
import { BOND_LEVELS, HEART_POINTS, MAX_HEARTS, bondHearts, bondLevel, petName } from '../../core/pet-bonds.js';
import { MEAL_COST, PET_FOODS, PET_BELONGINGS, petCareStatus } from '../../core/pet-care.js';
import { icon } from '../../ui/icons.js';
import { PET_GIFTS, petGifts } from '../../core/pet-gifts.js';
import { petGiftArt } from './pet-gift-art.js';

export const escapePetText = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
export const careIcon = kind => `<svg viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${kind === 'food' ? '<path d="M4 16h24l-3 9H7z"/><path d="M3 16h26M10 10c-3-3 3-3 0-6m7 6c-3-3 3-3 0-6m7 6c-3-3 3-3 0-6"/><path d="M13 20h6"/>' : kind === 'ball' ? '<circle cx="16" cy="16" r="11"/><path d="M6 12c8 3 12 8 14 14M12 6c3 8 8 12 14 14M8 24 24 8"/>' : '<path d="M8 17c-4-6 4-11 8-5 4-6 12-1 8 5l-8 8z"/><path d="M7 4v4M5 6h4m15-2v4m-2-2h4"/>'}</svg>`;
export function foodArt(food, fabric) {
  return `<svg viewBox="0 0 100 76" aria-hidden="true"><ellipse cx="50" cy="65" rx="33" ry="6" fill="#4c3025" opacity=".09"/><path d="M16 34h68l-8 26q-26 10-52 0z" fill="${fabric.color}"/><ellipse cx="50" cy="34" rx="34" ry="14" fill="${fabric.dark}"/><ellipse cx="50" cy="33" rx="29" ry="10" fill="#654c39"/>${[[33, 31], [43, 26], [57, 29], [67, 32], [50, 35], [38, 37], [62, 38]].map(([x, y], i) => `<ellipse cx="${x}" cy="${y}" rx="${food.id === 'supper' ? 8 : 5}" ry="4" transform="rotate(${i * 27} ${x} ${y})" fill="${food.color}"/>`).join('')}<path d="M17 35q33 23 66 0" fill="none" stroke="${fabric.color}" stroke-width="4"/><path d="M45 52q5-6 10 0l-5 5z" fill="#fff5e5"/></svg>`;
}
const MILESTONES = [['A warm welcome', 8], ['Naps beside you', 24], ['A little happy dance', 60]];
export function petCardMarkup(state, now) {
  const id = state.pet, bond = state.petBonds[id], level = bondLevel(bond), care = petCareStatus(bond, now);
  const fabric = PET_BELONGINGS.find(item => item.id === bond.care.fabric), petLabel = escapePetText(petName(state));
  const gifts = petGifts(bond), giftPreview = gifts.next || gifts.selected, hearts = bondHearts(bond);
  const nextMilestone = MILESTONES.find(([, points]) => bond.affection < points), chevron = '<span class="pet-row-chevron" aria-hidden="true"></span>';
  return `<div class="pet-card" data-pet-id="${id}">
    <header class="pet-card-identity"><h2>${petLabel}</h2><button id="pet-edit-name" aria-label="Rename ${petLabel}">${icon('build')}</button></header>
    <form id="pet-name-form" hidden><label class="sr-only" for="pet-name">Pet name</label><input id="pet-name" maxlength="24" value="${petLabel}" autocomplete="off" required><button type="submit">Save</button></form>
    <button type="button" id="pet-closeup" class="pet-closeup" aria-label="Pet ${petLabel}"></button>
    <div class="pet-hearts" role="meter" aria-label="Bond with ${petLabel}" aria-valuemin="0" aria-valuemax="${MAX_HEARTS}" aria-valuenow="${Math.floor(hearts)}" aria-valuetext="${Math.floor(hearts)} of ${MAX_HEARTS} hearts">${Array.from({ length: MAX_HEARTS }, (_, i) => `<i style="--fill:${Math.max(0, Math.min(1, hearts - i))}"></i>`).join('')}</div>
    <p class="pet-bond-title">${level.title}</p>
    <div class="pet-care-actions">
      <button id="pet-now" data-pet-ritual="cuddle" aria-label="Pet ${petLabel}">${careIcon('heart')}<strong>Pet</strong></button>
      <button id="pet-play" data-pet-ritual="play" aria-label="Play with ${petLabel}${care.playReady ? ', earn one heart' : `, heart in ${care.playMinutes} minutes`}">${careIcon('ball')}<strong>Play</strong>${care.playReady ? '' : `<small>${care.playMinutes}m ♡</small>`}</button>
      <button id="pet-feed" aria-expanded="false" aria-controls="pet-meals">${careIcon('food')}<strong>Feed</strong><small>${care.full ? 'Full' : `${MEAL_COST} ◉`}</small></button>
    </div>
    <div id="pet-meals" class="pet-meals" hidden>${PET_FOODS[id].map(food => `<button id="pet-meal-${food.id}" data-pet-meal="${food.id}" ${care.full || state.house.coins < MEAL_COST ? 'disabled' : ''}>${foodArt(food, fabric)}<span>${food.name}</span><small>${care.full ? `${care.mealMinutes}m` : `${MEAL_COST} ◉ · +1 ♡`}</small></button>`).join('')}<span class="pet-meal-note">${care.full ? `Full for ${care.mealMinutes} min` : state.house.coins < MEAL_COST ? `${MEAL_COST - state.house.coins} more coins` : `${state.house.coins} ◉`}</span></div>
    <p id="pet-ritual-status" class="pet-care-receipt" role="status"></p>
    <div class="pet-together"><button type="button" id="pet-study" class="pet-study">Study with ${petLabel}</button><button class="pet-invite" id="pet-invite" aria-label="Sit with ${petLabel}">${icon('cat')}Sit</button>${level.index >= 2 ? `<button class="pet-invite" id="pet-nap" aria-label="Nap beside ${petLabel}">${icon('moon')}Nap</button>` : ''}</div>
    <details class="pet-details pet-gifts" id="pet-gifts"><summary>${petGiftArt(giftPreview.id)}<span><strong>${gifts.next ? giftPreview.label : `Gifts from ${petLabel}`}</strong><small>${gifts.next ? `${gifts.remaining} min to go` : `${gifts.earned.length} gifts`}</small>${gifts.next ? `<i class="pet-gift-progress"><i style="width:${Math.min(100, bond.minutes / gifts.next.at * 100)}%"></i></i>` : ''}</span>${chevron}</summary><div class="pet-gift-options">${PET_GIFTS.map(gift => `<button id="pet-gift-${gift.id}" data-pet-gift="${gift.id}" ${bond.minutes < gift.at ? 'disabled' : ''} aria-pressed="${gifts.selected?.id === gift.id}" aria-label="${gift.label}${bond.minutes < gift.at ? `, ${gift.at} minutes together` : ', display beside your pet'}">${petGiftArt(gift.id)}<span>${gift.label}</span><small>${bond.minutes < gift.at ? `${gift.at} min` : gifts.selected?.id === gift.id ? 'In your room ♡' : 'Place in room'}</small></button>`).join('')}</div></details>
    <details class="pet-details" id="pet-belongings"><summary><i class="pet-row-swatch" style="--fabric:${fabric.color};--fabric-dark:${fabric.dark}"></i><span><strong>Little belongings</strong><small>${fabric.name}</small></span>${chevron}</summary><div class="pet-fabric-preview" style="--fabric:${fabric.color};--fabric-dark:${fabric.dark}"><div class="pet-quilt"><i>♡</i></div><span>Blanket & bowl</span></div><div class="pet-fabrics">${PET_BELONGINGS.map(item => `<button id="pet-fabric-${item.id}" data-pet-fabric="${item.id}" style="--fabric:${item.color};--fabric-dark:${item.dark}" aria-label="${item.name}${bond.care.belongings.includes(item.id) ? '' : `, ${item.price} coins`}" aria-pressed="${bond.care.fabric === item.id}"><i></i><small>${bond.care.belongings.includes(item.id) ? bond.care.fabric === item.id ? '✓' : '◦' : `${item.price} ◉`}</small></button>`).join('')}</div><div class="pet-ribbons" aria-label="Ribbon color">${BOND_LEVELS.map((item, index) => `<button id="pet-ribbon-${index}" data-pet-ribbon="${index}" aria-label="${item.keepsake}" aria-pressed="${bond.ribbon === index}" ${index > level.index ? 'disabled' : ''} style="--ribbon:${item.color}"><i>🎀</i><small>${index > level.index ? `${item.at / HEART_POINTS} ♥` : item.keepsake.split(' ')[0]}</small></button>`).join('')}</div></details>
    <details class="pet-details" id="pet-friendship"><summary><i class="pet-row-icon">${icon('heart')}</i><span><strong>Our friendship</strong><small>${nextMilestone ? `${nextMilestone[0]} at ${nextMilestone[1] / HEART_POINTS} ♥` : 'All shared'}</small></span>${chevron}</summary><ol class="pet-milestones">${MILESTONES.map(([label, points]) => `<li class="${bond.affection >= points ? 'is-unlocked' : ''}"><span>${label}</span><span>${bond.affection >= points ? '✓' : `${points / HEART_POINTS} ♥`}</span></li>`).join('')}</ol>${level.index >= 3 ? `<button id="pet-dance" class="pet-dance">${icon('sun')} Happy dance</button>` : ''}</details>
    <details class="pet-details" id="pet-collection"><summary><i class="pet-row-icon">${icon('cat')}</i><span><strong>My pets</strong><small>${state.pets.length} of ${Object.keys(PETS).length}</small></span>${chevron}</summary><div class="pet-options">${Object.values(PETS).map(entry => `<button data-pet-choice="${entry.id}" id="pet-choice-${entry.id}" aria-label="${state.pets.includes(entry.id) ? `Choose ${escapePetText(petName(state, entry.id))}` : `Meet ${entry.name}, ${entry.price} coins`}" aria-pressed="${id === entry.id}">${petArt(entry.id)}<span>${escapePetText(state.pets.includes(entry.id) ? petName(state, entry.id) : entry.name)}</span><small>${state.pets.includes(entry.id) ? id === entry.id ? '♡' : '' : `${entry.price} ◉`}</small></button>`).join('')}</div><div class="pet-adopt" id="pet-adopt" hidden></div></details>
  </div>`;
}
