import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { steps } from '../steps.mjs';
import { enterWilds, leaveWilds, holdKeys, resourceSample, wildsState, wildsFrameSample } from '../wilds.mjs';

const distance = (a,b) => Math.hypot(a.x-b.x, a.z-b.z);
const game = async app => (await wildsState(app)).game;
const visibleWords = `(() => { const root = document.querySelector('#wilds-page'), walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT), words = []; for (let n; n = walker.nextNode();) { const el = n.parentElement, style = getComputedStyle(el); if (/[a-zA-Z]/.test(n.textContent) && el.checkVisibility() && style.opacity !== '0' && el.getBoundingClientRect().width > 0) words.push(n.textContent.trim()); } return words; })()`;

export default {
  about: 'three.js feel box: lazy entry, real movement/combat/camera input, pause and five disposal cycles',
  async run(t) {
    const app = await t.open({ seed: 'three-rooms', scale: 2 });
    await app.settle();
    const initialSave = await app.saved();
    await steps.openHouse(app);
    const requests = [];
    await app.send('Network.enable');
    const unwatch = app.on(message => { if (message.method === 'Network.requestWillBeSent') requests.push(message.params.request.url); });
    const prior = await app.js('performance.getEntriesByType("resource").map(e => e.name)');
    t.check('room and island load no three.js or Wilds modules', !prior.some(url => /\/three[/.]|\/features\/wilds\/|\/models\/wilds\//.test(url)), prior.filter(url => /three|wilds/.test(url)));
    const baseline = await resourceSample(app, { retained: false });
    await enterWilds(app, { entry: 'button' });
    t.check('Forest loads the new three.js slice lazily', requests.some(url => /three|\/features\/wilds\//.test(url)), requests);
    unwatch();
    t.check('the island scene is freed during play', await app.js('window.__littleHours.house.diagnostics() == null'));
    t.check('play shows no visible words', (await app.js(visibleWords)).length === 0, await app.js(visibleWords));
    const start = await game(app);
    await holdKeys(app, [['w','KeyW']], 500);
    const walked = await game(app);
    t.check('W moves the player', distance(start.position,walked.position) > .3, {start,walked});
    await holdKeys(app, [['Shift','ShiftLeft'],['w','KeyW']], 500);
    const sprinted = await game(app);
    t.check('Shift sprint covers more ground and spends stamina', distance(walked.position,sprinted.position) > distance(start.position,walked.position) * 1.15 && sprinted.stamina < walked.stamina, {walked,sprinted});
    await app.key(' ', 'Space');
    await app.waitFor('window.__littleHours.forest.diagnostics().game.counters.jumps > 0', {what:'jump input'});
    t.check('Space jumps', (await game(app)).counters.jumps > start.counters.jumps);
    await t.sleep(700);
    await app.key('Control','ControlLeft');
    await t.sleep(100);
    t.check('Control dodges', (await game(app)).counters.dodges > start.counters.dodges);
    await t.sleep(850);
    const canvas = await app.box('#wilds-canvas');
    const beforeRightDodge = await game(app);
    await app.send('Input.dispatchMouseEvent', {type:'mousePressed',x:canvas.x,y:canvas.y,button:'right',buttons:2,clickCount:1});
    await app.send('Input.dispatchMouseEvent', {type:'mouseReleased',x:canvas.x,y:canvas.y,button:'right',buttons:0,clickCount:1});
    await t.sleep(100);
    t.check('right click also dodges', (await game(app)).counters.dodges > beforeRightDodge.counters.dodges);
    await t.sleep(850);
    for (let i = 0; i < 3; i++) { await app.click(canvas.x,canvas.y); await t.sleep(250); }
    await t.sleep(650);
    const combo = await game(app);
    t.check('three clicks produce the three-hit combo', combo.counters.lightAttacks >= start.counters.lightAttacks + 3 && combo.counters.hits >= 3 && combo.state.lastHit?.kind === 'light3', combo);
    await app.press(canvas.x,canvas.y); await t.sleep(850); await app.release(canvas.x,canvas.y); await t.sleep(700);
    const heavy = await game(app);
    t.check('holding left click releases a charged heavy that connects', heavy.counters.heavyAttacks > start.counters.heavyAttacks && heavy.counters.hits > combo.counters.hits && heavy.state.lastHit?.kind === 'heavy', heavy);
    await app.key('f','KeyF'); await t.sleep(100);
    const locked = await game(app);
    t.check('F locks onto the training dummy', locked.locked, locked);
    await app.key('f','KeyF'); await t.sleep(100);
    t.check('F releases lock cleanly', !(await game(app)).locked);
    const beforeCamera = (await game(app)).camera;
    await app.drag({x:canvas.x,y:canvas.y},{x:canvas.x+180,y:canvas.y+40});
    await app.send('Input.dispatchMouseEvent', {type:'mouseWheel',x:canvas.x,y:canvas.y,deltaX:0,deltaY:180});
    await t.sleep(300);
    const afterCamera = (await game(app)).camera;
    t.check('drag orbits and wheel zooms', Math.abs(afterCamera.yaw-beforeCamera.yaw) > .1 && Math.abs(afterCamera.distance-beforeCamera.distance) > .1, {beforeCamera,afterCamera});
    await t.shot(app,'feel-box');
    const beforeFrameRun = await game(app);
    const frames = await wildsFrameSample(app,5);
    t.check('orbit drag cancels its press and movement remains responsive', frames.game.action.kind === 'run' && distance(beforeFrameRun.position, frames.game.position) > 2, {before:beforeFrameRun.action,after:frames.game.action,distance:distance(beforeFrameRun.position,frames.game.position)});
    t.check('gameplay holds 60fps with no frame over 20ms', frames.fps >= 59 && frames.over20 === 0, frames);
    await app.key('Escape');
    const paused = await game(app);
    await holdKeys(app,[['w','KeyW']],400);
    t.check('Escape pauses and movement stops', paused.paused && distance(paused.position,(await game(app)).position) < .01, paused);
    await app.clickSel('#wilds-resume');
    t.check('Resume returns to play', !(await game(app)).paused);
    await leaveWilds(app);
    const coldReturn = await resourceSample(app);
    const warmup = [];
    for (let i = 0; i < 10; i++) { await enterWilds(app); await t.sleep(250); await leaveWilds(app); warmup.push(await resourceSample(app)); }
    const samples = [warmup.at(-1)];
    const entered = [];
    const returned = await app.js(`import('/src/features/house/island-forest.js').then(({ FOREST_TRAILHEAD }) => { const d = window.__littleHours.house.diagnostics(); return { place: d.strollPlace, actual: d.strollWorld, expected: FOREST_TRAILHEAD.position }; })`);
    t.check('leaving restores the trailhead', returned.place === 'forest-return' && Math.hypot(returned.actual.x - returned.expected[0], returned.actual.y - returned.expected[1], returned.actual.z - returned.expected[2]) < .001, returned);
    for (let i = 0; i < 5; i++) { const entry = i % 2 ? 'pin' : 'button'; await enterWilds(app, { entry }); await t.sleep(250); entered.push({ entry, ...await wildsState(app) }); await leaveWilds(app); samples.push(await resourceSample(app)); }
    t.check('each entry starts with consistent position and stamina', entered.every(s => distance(s.game.position, start.position) < .001 && s.game.stamina === start.stamina && s.game.counters.attack === 0), entered.map(s => ({entry:s.entry,position:s.game.position,stamina:s.game.stamina,counters:s.game.counters})));
    t.check('five exits restore the island with stable Babylon object counts', samples.every(s => JSON.stringify(s.counts) === JSON.stringify(samples[0].counts)), samples.map(s=>s.counts));
    t.check('five exits dispose all three.js GPU allocations and context', samples.every(s => s.forest.disposed?.geometries === 0 && s.forest.disposed?.textures === 0 && s.forest.disposed?.programs === 0 && s.forest.disposed?.contextLost === true), samples.map(s=>s.forest.disposed));
    const retentionSamples = [coldReturn, ...warmup, ...samples];
    t.check('every exit releases detached Wilds canvases and WebGL contexts', retentionSamples.every(s => s.retained.canvases.detachedWilds === 0 && s.retained.contexts.detachedWilds === 0), retentionSamples.map(s => s.retained));
    const heapGrowth = samples.at(-1).heap - samples[0].heap;
    t.check('warmed JS heap returns within 1MiB after five exits', heapGrowth <= 1048576, {baseline:baseline.heap,heaps:samples.map(s=>s.heap),growth:heapGrowth});
    const finalSave = await app.saved();
    t.check('Wilds does not award study gold or change the save', JSON.stringify(finalSave) === JSON.stringify(initialSave));
    writeFileSync(join(t.out,'wilds-evidence.json'),JSON.stringify({baseline,coldReturn,warmup,frames,entered,samples},null,2));
    await t.close(app);
  },
};
