const active = app => app.js('window.__littleHours.state.house.activeId');
const isOpen = app => app.js('document.getElementById("room-picker").open');

export default {
  about: 'room picker keyboard and dismiss, quick travel, single-room growth, phone sheet, and cancelling a door walk',
  async run(t) {
    const { check, steps, sleep } = t;
    let app = await t.open({ seed: 'three-rooms' });
    check('the navigator replaces the permanent room cards', !await isOpen(app) && (await app.box('#home-connections')).height < 75);
    check('the first room has no previous destination', await app.js('document.getElementById("previous-room").disabled') && await app.text('#room-route-count') === '1 / 3');
    await steps.openRoomPicker(app);
    check('the current room receives focus and an accessible current marker', await app.js('document.activeElement.dataset.houseGo === "studio"') && await app.attr('[data-house-go="studio"]', 'aria-current') === 'location');
    await t.shot(app, 'desktop');
    await app.key('ArrowRight');
    check('right arrow moves to the next room without travelling', await app.js('document.activeElement.dataset.houseGo === "garden"') && await active(app) === 'studio');
    await app.key('End');
    check('End reaches the last room', await app.js('document.activeElement.dataset.houseGo === "loft"'));
    await app.key('Home');
    await app.key('Escape');
    check('Escape closes the picker and restores the trigger', !await isOpen(app) && await app.js('document.activeElement.id === "room-switcher-toggle"') && await app.attr('#room-switcher-toggle', 'aria-expanded') === 'false');
    await steps.openRoomPicker(app);
    await app.click(10, 10);
    check('tapping the backdrop dismisses the picker', !await isOpen(app));
    await steps.openRoomPicker(app);
    const began = Date.now();
    await app.clickSel('[data-house-go="garden"]');
    check('selection closes the sheet and locks the route during transition', !await isOpen(app) && await app.js('document.getElementById("next-room").disabled && document.body.classList.contains("is-travelling") && !document.body.classList.contains("is-door-walking")'));
    await app.waitFor('window.__littleHours.state.house.activeId === "garden" && !document.body.classList.contains("is-travelling")');
    check('room switching finishes in under 1.5 seconds', Date.now() - began < 1500 * t.slow, `${Date.now() - began} ms`);
    check('arrival restores controls, location and heading focus', await app.text('#room-route-count') === '2 / 3' && await app.js('!document.getElementById("next-room").disabled && document.activeElement.id === "room-title"'));
    await app.clickSel('#next-room');
    await app.waitFor('window.__littleHours.state.house.activeId === "loft" && !document.body.classList.contains("is-travelling")');
    check('next room stops at the last room', await app.text('#room-route-count') === '3 / 3' && await app.js('document.getElementById("next-room").disabled'));
    await app.clickSel('#previous-room');
    await app.waitFor('window.__littleHours.state.house.activeId === "garden" && !document.body.classList.contains("is-travelling")');
    check('previous room moves back and saves the destination', (await app.saved()).house.activeId === 'garden');
    await steps.openRoomPicker(app);
    await app.clickSel('[data-house-go="garden"]');
    check('selecting the current room just closes the picker', !await isOpen(app) && !await app.js('document.body.classList.contains("is-travelling")'));
    await app.clickSel('#previous-room');
    await app.waitFor('window.__littleHours.state.house.activeId === "studio" && !document.body.classList.contains("is-travelling")');
    await app.settle();
    await app.clickTarget({ door: 'garden' });
    await app.waitFor('document.body.classList.contains("is-door-walking")');
    check('the scenic walk has a touch-sized cancel control', (await app.box('#cancel-room-travel')).width >= 44);
    await t.shot(app, 'walking');
    await app.clickSel('#cancel-room-travel');
    await sleep(500);
    check('cancel stops the walk without changing rooms', await active(app) === 'studio' && !await app.js('document.body.classList.contains("is-travelling")') && !await app.visible('#room-travel'));
    await app.settle();
    await app.clickTarget({ door: 'garden' });
    await app.waitFor('document.body.classList.contains("is-door-walking")');
    await app.key('Escape');
    check('Escape can cancel a second walk', await active(app) === 'studio' && !await app.js('document.body.classList.contains("is-travelling")'));
    await app.clickSel('#next-room');
    await app.waitFor('window.__littleHours.state.house.activeId === "garden" && !document.body.classList.contains("is-travelling")');
    check('quick travel still works after cancelling a walk', (await app.saved()).house.activeId === 'garden');
    await app.clickSel('#start-button');
    await steps.openRoomPicker(app);
    check('focusing explains why travel is unavailable inside the picker', await app.visible('#room-picker-notice'));
    await app.clickSel('[data-house-go="loft"]');
    check('focus refusal keeps the picker and current room', await isOpen(app) && await active(app) === 'garden');
    await app.key('Escape');
    await app.clickSel('#start-button');
    await t.close(app);

    app = await t.open({ seed: 'one-room', label: 'one room' });
    check('one room disables both travel arrows', await app.js('document.getElementById("previous-room").disabled && document.getElementById("next-room").disabled'));
    await steps.openRoomPicker(app);
    check('unbuilt rooms are offered as plans, separate from destinations', await app.js('document.querySelectorAll(".room-card").length === 1 && Boolean(document.querySelector("#room-grow [data-house-go= garden]"))'));
    await t.shot(app, 'one-room');
    await app.clickSel('#room-grow button');
    check('planning goes straight to the house page', !await isOpen(app) && await app.js('document.body.classList.contains("is-house")') && await app.text('#house-detail h2') === 'Greenhouse');
    await t.close(app);

    app = await t.open({ seed: 'three-rooms', width: 390, height: 844, reducedMotion: true, label: 'phone' });
    await steps.openRoomPicker(app);
    const phone = await app.js(`(() => { const r = document.getElementById('room-picker').getBoundingClientRect(); return { bottom: r.bottom, width: r.width, overflow: document.documentElement.scrollWidth > innerWidth, cards: [...document.querySelectorAll('.room-card')].map(el => { const b = el.getBoundingClientRect(); return b.width >= 44 && b.height >= 44 && b.left >= 0 && b.right <= innerWidth; }) }; })()`);
    check('phone: a bottom sheet with three readable touch targets and no overflow', Math.abs(phone.bottom - 844) < 2 && phone.width === 390 && !phone.overflow && phone.cards.every(Boolean), phone);
    await t.shot(app, 'phone');
    await app.clickSel('[data-house-go="loft"]');
    check('reduced motion arrives immediately without an animation', await active(app) === 'loft' && !await app.js('document.body.classList.contains("is-travelling")') && !await isOpen(app));
    await steps.openRoomPicker(app);
    await app.clickSel('#room-picker-house');
    check('the picker also reaches the full house', !await isOpen(app) && await app.js('document.body.classList.contains("is-house")'));
    await t.close(app);

    app = await t.open({ seed: 'three-rooms', width: 320, height: 740, reducedMotion: true, label: 'small phone' });
    const small = await app.js(`(() => { const route = document.querySelector('.room-route').getBoundingClientRect(), wide = document.querySelector('.home-wide').getBoundingClientRect(), toggle = document.getElementById('room-switcher-toggle'); return { fits: route.right <= wide.left && wide.right <= innerWidth, nowrap: getComputedStyle(toggle).whiteSpace === 'nowrap', labelled: Boolean(document.querySelector('.home-wide').getAttribute('aria-label')) }; })()`);
    check('small phone: room controls keep one line, do not collide and stay labelled', small.fits && small.nowrap && small.labelled, small);
    await steps.openRoomPicker(app);
    check('small phone: the picker stays within the viewport', await app.js('document.getElementById("room-picker").getBoundingClientRect().width === 320 && document.documentElement.scrollWidth === 320'));
    await t.shot(app, 'small-phone');
    await t.close(app);
  },
};
