import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { steps } from '../steps.mjs';
import { enterWilds, leaveWilds } from '../wilds.mjs';
import { fightState, walkTo, playFight, inputResponse, recordFight } from '../encounter.mjs';
import { followTrail, climbFace, glideToward, seekShore } from '../valley.mjs';

const distance = (a, b) => Math.hypot(a.x - b.x, a.z - b.z);
const action = (app, name) => app.clickSel(`[data-wilds-action="${name}"]`);

export default {
  about: 'one continuous Wilds visit: buy a sword, care for the partner, climb, discover, glide, swim, return to defeat the guardian and persist progression',
  async run(t) {
    const app = await t.open({ seed: 'pet-shop', scale: 2 });
    const events = [], latency = {}, seenModes = new Set();
    let stopRecording;
    const observe = game => {
      seenModes.add(game.state.player.mode);
      const event = game.exploration.lastEvent;
      if (!events.some(item => item.serial === event?.serial) && event) events.push({ ...event, position: game.position, camera: game.camera, counts: game.state.counts });
    };
    try {
      await app.settle();
      const initial = await app.saved();
      const initialBonds=await app.js('structuredClone(window.__littleHours.state.petBonds)');
      t.check('the merchant test starts with 120 earned study coins', initial.house.coins === 120, initial.house.coins);
      await steps.openHouse(app); await enterWilds(app, { entry: 'button' });
      stopRecording = await recordFight(app, join(t.out, 'valley-play'));
      await walkTo(app, -3, 4);
      await app.key('e', 'KeyE');
      await app.waitFor('window.__littleHours.forest.diagnostics().game.paused', { what: 'the camp menu' });
      await action(app, 'tab-merchant'); await action(app, 'buy:trail-sword');
      await app.waitFor('window.__littleHours.forest.diagnostics().game.exploration.save.gear.includes("trail-sword")',{what:'the purchase completing its shared save transaction'});
      const purchased = await fightState(app);
      t.check('the merchant deducts 35 coins and equips a lasting stronger sword', purchased.exploration.coins === 85 && purchased.exploration.save.gear.includes('trail-sword') && purchased.exploration.stats.attack > 1, purchased.exploration);
      await app.clickSel('#wilds-resume');
      await walkTo(app, -7, 2);
      latency.whistle = await inputResponse(app, () => app.key('r', 'KeyR'), 'game.exploration.counts.whistles > 0');
      await app.waitFor('window.__littleHours.forest.diagnostics().game.exploration.near?.kind === "pet"', { what: 'the partner arriving beside the player', timeout: 10000 });
      latency.pet = await inputResponse(app, () => app.key('e', 'KeyE'), 'game.exploration.counts.pets > 0');
      const cared = await fightState(app); observe(cared);
      t.check('whistle and petting respond within 100ms', Object.values(latency).every(result => result.responded && result.ms < 100), latency);
      t.check('the exploring companion can be called and petted', cared.exploration.counts.whistles > 0 && cared.exploration.counts.pets > 0 && !cared.paused, cared.exploration.counts);
      await followTrail(app, [[-19,2],[-21,-28],[-18,-65]], observe);
      const vista = await fightState(app);
      t.check('the western trail reaches the vista without forcing a guardian fight', vista.encounter.status === 'dormant' && distance(vista.position, { x: -18, z: -65 }) < 1, vista.position);
      await t.shot(app, 'valley-vista');
      await followTrail(app, [[-10,-48],[-18,-65],[-34,-99],[-55,-134],[-72,-180]], observe);
      const meadow = await fightState(app); observe(meadow);
      t.check('walking past trail herbs picks them and lights the meadow checkpoint', meadow.exploration.counts.herbs > 0 && meadow.exploration.save.lit.includes('meadow') && meadow.exploration.save.checkpoint === 'meadow', meadow.exploration);
      await app.key('e', 'KeyE'); await action(app, 'tab-camp'); await action(app, 'rest-night');
      await app.waitFor('window.__littleHours.forest.diagnostics().game.exploration.save.hour === 21',{what:'the night rest being saved'});
      const night = await fightState(app);
      t.check('camp rest advances to night and heals fully', night.exploration.save.hour === 21 && night.encounter.player.health === night.encounter.player.maxHealth, night.exploration.save);
      await action(app, 'rest-morning');
      await app.waitFor('window.__littleHours.forest.diagnostics().game.exploration.save.hour === 7',{what:'the morning rest being saved'});
      const morning = await fightState(app);
      t.check('camp rest advances to the next morning without earning gold', morning.exploration.save.hour === 7 && morning.exploration.coins === 85, morning.exploration.save);
      await app.clickSel('#wilds-resume');
      await followTrail(app, [[-78,-254],[-92,-286],[-95,-305]], observe);
      const cliff = (await fightState(app)).landmarks.cliff;
      const climbed = await climbFace(app, cliff, observe);
      t.check('real directional input climbs and mantles onto the seed cliff', climbed.state.counts.climb > 0 && climbed.grounded && Math.abs(climbed.position.y - cliff.top) < .05, { position: climbed.position, counts: climbed.state.counts, mode: climbed.state.player.mode });
      await walkTo(app, cliff.x, cliff.z, { tolerance: .65 });
      await t.shot(app, 'valley-cliff-unclaimed');
      const coinsBeforeFind = (await fightState(app)).exploration.coins;
      await app.key('e', 'KeyE');
      await app.waitFor('window.__littleHours.forest.diagnostics().game.exploration.save.found.includes("cliff-seed")', { what: 'claiming the summit secret', timeout: 3000 });
      const found = await fightState(app); observe(found);
      t.check('the summit secret grants XP and stamina without gold', found.exploration.save.xp >= 35 && found.exploration.stats.stamina >= 120 && found.exploration.coins === coinsBeforeFind, found.exploration);
      await t.shot(app, 'valley-cliff-secret');
      await app.waitFor('window.__littleHours.forest.diagnostics().game.stamina >= window.__littleHours.forest.diagnostics().game.state.player.maxStamina - 1', { what: 'catching a breath before opening the cape', timeout: 8000 });
      const flight = await glideToward(app, -145, -355, game => { observe(game); });
      t.check('a real jump and second Space open the cape and travel through the valley', flight.opened && flight.game.state.counts.glide > 0 && flight.distance > 15, flight);
      await seekShore(app, -160, -354, observe);
      const swimmingBefore = (await fightState(app)).state.counts.swim;
      await walkTo(app, -160, -390, { tolerance: .8, timeout: 35000 });
      const swimmer = await fightState(app); observe(swimmer);
      t.check('walking into the real lake swims at its water level', swimmer.state.counts.swim > swimmingBefore && swimmer.state.player.mode === 'swim' && Math.abs(swimmer.position.y + 44.45) < .05, { position: swimmer.position, mode: swimmer.state.player.mode, stamina: swimmer.stamina });
      const beforeCatchUp = { gap: distance(swimmer.encounter.pet, swimmer.position), player: swimmer.position, pet: swimmer.encounter.pet };
      t.check('the companion entering the lake paddles at its surface', swimmer.encounter.pet.swimming && Math.abs(swimmer.encounter.pet.ground + 44.22) < .05, beforeCatchUp);
      await app.waitFor('(() => { const game = window.__littleHours.forest.diagnostics().game, pet = game.encounter.pet; return pet.swimming && Math.abs(pet.ground + 44.22) < .05 && Math.hypot(pet.x - game.position.x, pet.z - game.position.z) < 3; })()', { what: 'the paddling companion catching up beside the stopped swimmer', timeout: 8000 });
      const caughtUp = await fightState(app); observe(caughtUp);
      const afterCatchUp = { gap: distance(caughtUp.encounter.pet, caughtUp.position), player: caughtUp.position, pet: caughtUp.encounter.pet };
      t.check('the companion follows beside the stopped swimmer within eight seconds', afterCatchUp.gap < 3 && caughtUp.encounter.pet.swimming && Math.abs(caughtUp.encounter.pet.ground + 44.22) < .05 && (beforeCatchUp.gap < 3 || afterCatchUp.gap < beforeCatchUp.gap), { before: beforeCatchUp, after: afterCatchUp });
      await t.shot(app, 'valley-lake-swim');
      await seekShore(app, -160, -354, observe);
      await followTrail(app, [[-200,-350],[-230,-375],[-230,-400],[-220,-414]], observe);
      const shore = await fightState(app); observe(shore);
      t.check('the shore camp becomes the last checkpoint', shore.exploration.save.checkpoint === 'shore' && shore.exploration.save.lit.includes('shore'), shore.exploration.save);
      await t.shot(app, 'valley-shore-camp');
      await followTrail(app, [[-230,-400],[-230,-375],[-200,-350],[-160,-340],[-128,-340],[-128,-286],[-92,-286],[-78,-254],[-72,-180]], observe);
      await app.key('e', 'KeyE');
      await app.waitFor('window.__littleHours.forest.diagnostics().game.paused', { what: 'the meadow camp menu before the guardian' });
      await action(app, 'tab-camp'); await action(app, 'rest-morning');
      await app.waitFor('window.__littleHours.forest.diagnostics().game.exploration.save.checkpoint === "meadow" && window.__littleHours.forest.diagnostics().game.encounter.player.health === window.__littleHours.forest.diagnostics().game.encounter.player.maxHealth', { what: 'resting at the meadow checkpoint' });
      const rested = await fightState(app);
      t.check('the return journey rests at meadow without spending more study gold', rested.exploration.save.checkpoint === 'meadow' && rested.exploration.coins === 85 && rested.encounter.player.health === rested.encounter.player.maxHealth, rested.exploration);
      await app.clickSel('#wilds-resume');
      await followTrail(app, [[-55,-134],[-34,-99],[-18,-65],[0,-38]], observe);
      await app.waitFor('window.__littleHours.forest.diagnostics().game.stamina >= window.__littleHours.forest.diagnostics().game.state.player.maxStamina - 1', { what: 'catching a breath outside the standing stones', timeout: 12000 });
      await walkTo(app, 0, -34, { tolerance: .5 });
      const arrival = await fightState(app);
      t.check('the same exploration visit returns to start the guardian fight', arrival.encounter.status === 'fighting', arrival.encounter);
      const frames = await stopRecording(); stopRecording = null;
      t.check('exploration was recorded with climbing, gliding and swimming frames', frames.length > 50 && ['climb','glide','swim'].every(mode => seenModes.has(mode)), { frames: frames.length, modes: [...seenModes] });
      const fightActions = new Set(), fightPhases = new Set();
      const result = await playFight(app, { out: join(t.out, 'final-fight'), onState(game) { observe(game); fightActions.add(game.encounter.boss.action.kind); fightPhases.add(game.encounter.boss.phase); } });
      const fight = result.game.encounter;
      t.check('the bought sword and real combat inputs defeat the guardian in the same visit', fight.status === 'won' && fight.counts.hits > 0 && result.events.some(event => event.event === 'dodge'), { status: fight.status, counts: fight.counts, health: fight.player.health });
      t.check('the continuous journey includes phase two and companion combat', fightPhases.has(2) && fight.counts.petHits > 0 && fight.counts.petSkills > 0, { actions: [...fightActions], phases: [...fightPhases], counts: fight.counts });
      t.check('the final fight has recorded frames for review', result.frames.length > 20, result.frames.length);
      await app.waitFor('window.__littleHours.forest.diagnostics().game.exploration.save.guardian === true', { what: 'the guardian victory being persisted', timeout: 5000 });
      await t.shot(app, 'valley-guardian-victory');
      writeFileSync(join(t.out, 'valley-final-fight.json'), JSON.stringify({ ...result, actions: [...fightActions], phases: [...fightPhases] }, null, 2));
      await leaveWilds(app);
      const saved = await app.saved();
      t.check('purchases and discoveries persist and only purchases spend study coins', saved.house.coins === 85 && saved.wilds.gear.includes('trail-sword') && saved.wilds.found.includes('cliff-seed') && saved.wilds.xp >= 195 && saved.wilds.guardian === true && saved.wilds.checkpoint === 'meadow', saved.wilds);
      t.check('exploration leaves room pet bonds unchanged', JSON.stringify(saved.petBonds) === JSON.stringify(initialBonds), {before:initialBonds,after:saved.petBonds});
      await enterWilds(app);
      const returned = await fightState(app), checkpoint = returned.landmarks.camps.find(camp => camp.id === 'meadow');
      t.check('reentry restores the saved meadow checkpoint, guardian victory and progression', distance(returned.position, checkpoint) < .05 && Math.abs(returned.position.y - checkpoint.y) < .05 && returned.exploration.save.found.includes('cliff-seed') && returned.exploration.save.guardian === true && returned.exploration.stats.attack > 1 && returned.exploration.coins === 85, returned.exploration);
      await leaveWilds(app);
      t.check('exploration has no browser errors', app.errors.length === 0, app.errors);
      writeFileSync(join(t.out, 'valley-evidence.json'), JSON.stringify({ latency, events, modes: [...seenModes], frames: frames.length, purchased: purchased.exploration, found: found.exploration, guardian: fight, returned }, null, 2));
    } finally {
      writeFileSync(join(t.out, 'valley-path.json'), JSON.stringify({ latency, events, modes: [...seenModes], final: await fightState(app).catch(() => null) }, null, 2));
      if (stopRecording) await stopRecording().catch(() => {});
      await t.close(app);
    }
  },
};
