import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { steps } from '../steps.mjs';
import { enterWilds, leaveWilds } from '../wilds.mjs';
import { fightState, walkTo, playFight, inputResponse, recordFight } from '../encounter.mjs';

export default {
  about: 'walk to the standing stones, fight the guardian with a partner and return to the island',
  async run(t) {
    const app = await t.open({ seed: 'three-rooms', scale: 2 });
    await app.settle(); const saved = await app.saved();
    const initialBonds=await app.js('structuredClone(window.__littleHours.state.petBonds)');
    await steps.openHouse(app); await enterWilds(app, { entry: 'button' });
    const latency = {};
    latency.move = await inputResponse(app, () => app.send('Input.dispatchKeyEvent', {type:'keyDown',key:'w',code:'KeyW'}), 'game.action.kind === "run"');
    await app.send('Input.dispatchKeyEvent', {type:'keyUp',key:'w',code:'KeyW'});
    latency.jump = await inputResponse(app, () => app.key(' ', 'Space'), 'game.action.kind === "jump"');
    await t.sleep(1000);
    latency.dodge = await inputResponse(app, () => app.key('Control', 'ControlLeft'), 'game.action.kind === "dodge"');
    await t.sleep(850);
    latency.lock = await inputResponse(app, () => app.key('f', 'KeyF'), 'game.locked');
    await app.key('f', 'KeyF');
    const canvas = await app.box('#wilds-canvas');
    latency.attack = await inputResponse(app, () => app.press(canvas.x,canvas.y), 'game.action.kind === "charge"');
    await app.release(canvas.x,canvas.y); await t.sleep(850);
    latency.mute = await inputResponse(app, () => app.key('m', 'KeyM'), 'game.muted');
    await app.key('m','KeyM');
    t.check('movement, jump, dodge, attack, lock and mute respond within 100ms', Object.values(latency).every(item => item.responded && item.ms < 100), latency);
    writeFileSync(join(t.out,'input-latency.json'),JSON.stringify(latency,null,2));
    await walkTo(app, 2.5, 2);
    await walkTo(app, 2.5, -12.8);
    const arrival = await fightState(app);
    t.check('the guardian loads a weighted Blender rig through the Forest entrance',arrival.actors?.stag?.skinnedMeshes>0 && arrival.actors.stag.bones>10,arrival.actors?.stag);
    t.check('walking into the stone ring starts the guardian encounter', arrival.encounter.status === 'fighting', arrival.encounter.status);
    latency.partner = await inputResponse(app, () => app.key('q','KeyQ'), 'game.encounter.counts.petSkills > 0');
    t.check('the partner skill responds within 100ms', latency.partner.responded && latency.partner.ms < 100, latency.partner);
    writeFileSync(join(t.out,'input-latency.json'),JSON.stringify(latency,null,2));
    await t.shot(app, 'arrival');
    const actions = new Set(), stages = new Set(), clips = new Set();
    const result = await playFight(app, { out: t.out, onState(game) { actions.add(game.encounter.boss.action.kind); stages.add(game.encounter.boss.phase); clips.add(game.actors?.stag?.clip); } });
    writeFileSync(join(t.out, 'fight-evidence.json'), JSON.stringify({ ...result, actions: [...actions], phases: [...stages] }, null, 2));
    const fight = result.game.encounter;
    t.check('real movement and sword input defeat the guardian', fight.status === 'won', {status:fight.status,health:fight.player.health,boss:fight.boss.health,counts:fight.counts});
    t.check('the fight reaches phase two and a charge stuns on a stone', stages.has(2) && fight.counts.stoneStuns > 0, {phases:[...stages],counts:fight.counts});
    t.check('the recorded fight includes all four guardian attacks', ['charge','sweep','stomp','roots'].every(kind => actions.has(kind)), [...actions]);
    t.check('all guardian threats play their matching baked animation clips',['charge','sweep','stomp','roots','stunned','phase','defeat'].every(kind=>clips.has(kind)),[...clips]);
    t.check('the companion visibly contributes attacks and a commanded dash', fight.counts.petHits > 0 && fight.counts.petSkills > 0, fight.counts);
    t.check('late dodges create a flurry opening', fight.counts.perfectDodges > 0, fight.counts);
    t.check('real play is recorded for frame review', result.frames.length > 20, result.frames.length);
    const stopDefeatRecording=await recordFight(app,join(t.out,'defeat'));
    await t.sleep(3250);
    const defeatFrames=await stopDefeatRecording();
    const victoryCamera = await fightState(app);
    t.check('the baked kneeling defeat finishes its leaf transition',victoryCamera.actors.stag.clip==='defeat' && !victoryCamera.actors.stag.visible && defeatFrames.length>10,{actor:victoryCamera.actors.stag,frames:defeatFrames.length});
    t.check('victory releases lock without collapsing the camera into the player', !victoryCamera.locked && Math.hypot(...victoryCamera.camera.position.map((value,index)=>value-victoryCamera.camera.target[index])) > 2.5, victoryCamera.camera);
    await t.shot(app, 'outcome'); await leaveWilds(app);
    const afterVictory=await app.saved();
    t.check('the guardian grants one-time XP and Wolf without study gold or bond changes',afterVictory.wilds?.guardian===true && afterVictory.wilds.xp===160 && afterVictory.house.coins===saved.house.coins && JSON.stringify(afterVictory.petBonds)===JSON.stringify(initialBonds),afterVictory.wilds);
    await enterWilds(app);
    await walkTo(app, 2.5, 2); await walkTo(app, 2.5, -12.8);
    await app.js(`(() => { window.__lhFightFrames = []; window.__lhFightMeasuring = true; let last = 0; const frame = now => { if (last) window.__lhFightFrames.push(now - last); last = now; if (window.__lhFightMeasuring) requestAnimationFrame(frame); }; requestAnimationFrame(frame); return true; })()`);
    const measured = await playFight(app);
    await t.sleep(3250);
    const performance = await app.js(`(() => { window.__lhFightMeasuring = false; const frames = window.__lhFightFrames, sorted = frames.toSorted((a,b) => a-b); return { frames: frames.length, fps: frames.length * 1000 / frames.reduce((a,b) => a+b,0), maxMs: Math.max(...frames), p95Ms: sorted[Math.ceil(sorted.length * .95)-1], over20: frames.filter(ms => ms > 20).length }; })()`);
    writeFileSync(join(t.out, 'fight-performance.json'), JSON.stringify({ performance, game: measured.game }, null, 2));
    t.check('the fight wins again without recording overhead', measured.game.encounter.status === 'won', measured.game.encounter);
    t.check('the Retina fight holds 60fps with no frame over 20ms', performance.fps >= 59 && performance.over20 === 0, performance);
    await leaveWilds(app);
    await enterWilds(app);
    await walkTo(app,2.5,2); await walkTo(app,2.5,-12.8); await walkTo(app,0,-22);
    const stopRecoveryRecording = await recordFight(app,join(t.out,'recovery'));
    await app.waitFor('window.__littleHours.forest.diagnostics().game.encounter.counts.defeats > 0', {what:'the guardian defeating an undefended player',timeout:90000});
    await app.waitFor('window.__littleHours.forest.diagnostics().game.encounter.status === "dormant"', {what:'waking at camp',timeout:10000});
    const recovered = await fightState(app); await stopRecoveryRecording();
    t.check('defeat returns the player and partner to camp fully healed', Math.hypot(recovered.position.x,recovered.position.z-2)<.01 && recovered.encounter.player.health===recovered.encounter.player.maxHealth && recovered.encounter.pet.health===recovered.encounter.pet.maxHealth, recovered.encounter);
    t.check('defeat loses no possessions or study gold', JSON.stringify(await app.saved()) === JSON.stringify(afterVictory));
    await t.sleep(500);
    const campCamera = await fightState(app);
    t.check('waking at camp restores a comfortable follow camera', Math.hypot(...campCamera.camera.position.map((value,index)=>value-campCamera.camera.target[index])) > 3, campCamera.camera);
    await t.shot(app,'recovery'); await leaveWilds(app);
    await t.close(app);
  },
};
